# Default values for clusters.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster: 
  baseDomain: sandbox317.opentlc.com
  name: blerg
  region: eu-west-2
  env: prod

clusterSet:
  enabled: true
  name: demo

sshPubKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAJRJuCD7XjKfVCpY3uLI/4uhgeRKpJvmKrgG/8lNZ+2 prajendr@prajendr-mac'

sealedSecrets: true

secrets:
  aws_access_key_id: 'changeme'
  aws_secret_access_key: 'changeme'
  pullSecret: 'changeme'
  sshPrivateKey: 'changeme'
